<?php
/**
 * Страница "Форма добавления / редактирования меню".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Add / edit menu form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the menu list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Menu name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Menu description;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Visible.</b> Menu visibility on the site.</li>
    </ul>
</article>