<?php
/**
 * Страница "Форма добавления / редактирования меню".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования меню</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов списка меню или выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название.</b> Название меню;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание меню;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Видимый.</b> Видимость меню на сайте.</li>
    </ul>
</article>