<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Меню сайта</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Модуль предназначен для создания меню сайта.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список меню сайта</a></li>
        <li><a href="<?= $url('items-grid') ?>">Список пунктов меню сайта</a></li>
        <li><a href="<?= $url('form') ?>">Форма добавления / редактирования меню</a></li>
        <li><a href="<?= $url('item-form') ?>">Форма добавления / редактирования пункта меню</a></li>
    </ul>
</article>