<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.

 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Site menu</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The module is designed to create a site menu.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of sitem menu</a></li>
        <li><a href="<?= $url('items-grid') ?>">List of sitem menu items</a></li>
        <li><a href="<?= $url('form') ?>">Add / edit menu form</a></li>
        <li><a href="<?= $url('item-form') ?>">Add / edit menu item form</a></li>
    </ul>
</article>