<?php
/**
 * Страница "Форма добавления / редактирования пункта меню".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Add / edit menu item form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/item-form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the menu list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Language.</b> The language for which the menu item will be displayed;</li>
        <li><b>Name.</b> Menu item name;</li>
        <li><b>Description.</b> Description of menu item;</li>
        <li><b>Title.</b> Title is the attribute (title) of the alternative title of the menu item that appears when you hover over it;</li>
        <li><b>Class CSS.</b> Custom CSS class for a menu item. Used to give a specific menu item its own style;</li>
        <li><b>Relationship to link.</b> Specifies the value for the rel attribute of a menu item;</li>
        <li><b>Type.</b> Menu item type (link to article, custom link...);</li>
        <li><b>URL.</b> The URL to jump to when clicking on a menu item;</li>
        <li><b>Icon URL.</b> Menu item icon URL;</li>
        <li><b>Open in new window.</b> Open a new window when you navigate to a specified URL;</li>
        <li><b>Visible.</b> Show or hide menu item.</li>
    </ul>
</article>