<?php
/**
 * Страница "Форма добавления / редактирования пункта меню".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования пункта меню</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/item-form.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов списка пунктов меню или выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Язык.</b> Язык для которого будет отображаться пункт меню;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название.</b> Название пункта меню;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание пункта меню;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Заголовок.</b> Заголовок - это атрибут (title) альтернативного заголовка пункта меню, который появляется при наведении курсора на него;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Класс CSS.</b> Индивидуальный класс CSS для пункта в меню. Применяется для придания отдельно взятому пункту индивидуального стиля;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Отношение к ссылке.</b> Указывает значение атрибуту rel пункта меню;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Тип.</b> Тип пункта меню (ссылка на статью, произвольная ссылка...);</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>URL-адрес.</b> URL-адрес перехода при нажатии на пункт меню;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>URL-адрес значка.</b> URL-адрес значка пункта меню;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Открыть в новом окне.</b> Открытие нового окна при переходе по указанному URL-адресу;</li>
        <li><b><span class="g-help-fld g-help-fld_checkbox"></span> Видимый.</b> Показать или скрыть пункт меню.</li>
    </ul>
</article>