<?php
/**
 * Страница "Пункты меню сайта".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Site menu items</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/items-grid.png' ?>" />
    </div>
    <p>The list displays all items of the site menu selected from the list.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>№.</b> The index number of the menu item;</li>
        <li><b>ID.</b> Menu item identifier;</li>
        <li><b>Name.</b> Menu item name;</li>
        <li><b>Description.</b> Description of menu item;</li>
        <li><b>Language.</b> The language for which the menu item will be displayed;</li>
        <li><b>Title.</b> Title is the attribute (title) of the alternative title of the menu item that appears when you hover over it;</li>
        <li><b>Class CSS.</b> Custom CSS class for a menu item. Used to give a specific menu item its own style;</li>
        <li><b>Relationship to link.</b> Specifies the value for the rel attribute of a menu item.;</li>
        <li><b>Type.</b> Menu item type (link to article, custom link...);</li>
        <li><b>URL.</b> The URL to jump to when clicking on a menu item;</li>
        <li><b>Open site page.</b> Navigate to the URL specified in the menu item;</li>
        <li><b>Sub-items.</b> Count of sub-items in a menu item;</li>
        <li><b>Open in new window.</b> Indicates that a new window will open when the specified URL is clicked;</li>
        <li><b>Visible.</b> Show or hide menu item;</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
    <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-add.svg' ?>" /> <b>Add.</b> Shows a form to add a menu item;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Delete.</b> Delete the selected menu items;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Delete all menu items;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Shows a form for editing a menu item;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects menu items;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refreshes the list of menu items;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Bar to display information about a menu item;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Shows the help window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Shows a form for filtering records in a list.</li>
    </ul>
</article>